/**
 * Deploy ZwickToken to RSK network
 *
 * Requirements:
 *   - PRIVATE_KEY env var (deployer wallet)
 *   - ORACLE_ADDRESS env var (price oracle wallet address)
 *   - RSK_NETWORK env var: 'testnet' (default) or 'mainnet'
 *
 * Usage:
 *   cd rbtccore && node contracts/deploy.js
 */
require('dotenv').config({ path: '../.env' });
const { ethers } = require('ethers');
const { provider, networkConfig } = require('../connect');

// ZwickToken ABI (constructor only — generated by solc in production)
const ZwickToken_ABI = [
  'constructor(uint256 initialRateUsdCents, address oracleAddress)',
  'function name() view returns (string)',
  'function symbol() view returns (string)',
  'function totalSupply() view returns (uint256)',
  'function owner() view returns (address)',
  'function rbtcUsdRate() view returns (uint256)',
  'function mint(address to, uint256 amount)',
  'function burn(uint256 amount)',
  'function transfer(address to, uint256 amount) returns (bool)',
  'function balanceOf(address account) view returns (uint256)',
  'function updateRate(uint256 newRateUsdCents)',
  'function rbtcToZwick(uint256 rbtcWei) view returns (uint256)',
];

// Minimal bytecode placeholder — replace with real compiled output from solc/hardhat
// In production: compile with `npx hardhat compile` and import artifacts
const ZwickToken_BYTECODE = process.env.ZWICK_BYTECODE || '';

async function main() {
  const privateKey   = process.env.PRIVATE_KEY;
  const oracleAddr   = process.env.ORACLE_ADDRESS;

  if (!privateKey)  { console.error('Set PRIVATE_KEY in .env'); process.exit(1); }
  if (!oracleAddr)  { console.error('Set ORACLE_ADDRESS in .env'); process.exit(1); }
  if (!ZwickToken_BYTECODE) {
    console.error(
      'Set ZWICK_BYTECODE in .env (compile ZwickToken.sol with solc or hardhat).\n' +
      'Tip: npx hardhat compile && cat artifacts/contracts/ZwickToken.sol/ZwickToken.json | jq .bytecode'
    );
    process.exit(1);
  }

  const wallet = new ethers.Wallet(privateKey, provider);
  console.log(`Deployer: ${wallet.address}`);
  console.log(`Network:  ${networkConfig.name} (chainId ${networkConfig.chainId})`);

  // Initial rate: $60,000 per RBTC (in cents)
  const initialRateUsdCents = 6_000_000n;

  const factory = new ethers.ContractFactory(ZwickToken_ABI, ZwickToken_BYTECODE, wallet);
  const contract = await factory.deploy(initialRateUsdCents, oracleAddr);

  console.log(`Deploying ZwickToken… tx: ${contract.deploymentTransaction().hash}`);
  await contract.waitForDeployment();

  const address = await contract.getAddress();
  console.log(`ZwickToken deployed at: ${address}`);
  console.log(`Explorer: ${networkConfig.explorer}/address/${address}`);
  console.log(`\nAdd to your .env:\nZWICK_TOKEN_ADDRESS=${address}`);
}

main().catch((err) => { console.error(err); process.exit(1); });
